<a class="{{ request()->is('admin/director-report') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
    href="{{ url('/admin/director-report') }}">Director Report</a>
<a class="{{ request()->is('admin/director-report-list') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
    href="{{ url('/admin/director-report-list') }}">Director Report List</a>
<a class="{{ request()->is('admin/details-of-shareholding') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
    href="{{ url('/admin/details-of-shareholding') }}">Details Of Shareholding</a>
<a class="{{ request()->is('admin/details-of-shareholding-list') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
    href="{{ url('/admin/details-of-shareholding-list') }}">Details Of Shareholding List</a>

<button class="collapsible">All Pages</button>
<div class="content">
    <a class="{{ request()->is('admin/shareholding-position') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/shareholding-position') }}">Shareholding Position</a>
    <a class="{{ request()->is('admin/shareholding-list') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/shareholding-list') }}">Shareholding Position List</a>
    <a class="{{ request()->is('admin/sale-buy-declaration') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/sale-buy-declaration') }}">Sale buy declaration</a>
    <a class="{{ request()->is('admin/sale-buy-declaration-list') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/sale-buy-declaration-list') }}">Sale buy declaration list</a>
    <a class="{{ request()->is('admin/corporate-governance') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/corporate-governance') }}">Corporate Governance</a>
    <a class="{{ request()->is('admin/notice-investor') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/notice-investor') }}">Notice Investor</a>
    <a class="{{ request()->is('admin/notice-investor-list') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/notice-investor-list') }}">Notice Investor list</a>
    <a class="{{ request()->is('admin/price-sensitive') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/price-sensitive') }}">Price Sensitive Information</a>
    <a class="{{ request()->is('admin/price-sensitive-list') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/price-sensitive-list') }}">Price Sensitive List</a>
    <a class="{{ request()->is('admin/distribution-policy') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/distribution-policy') }}">Distribution Policy</a>
    <a class="{{ request()->is('admin/pending-dividend') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/pending-dividend') }}">Unpaid/Unclaimed Dividend</a>
    <a class="{{ request()->is('admin/pending-dividend-list') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/pending-dividend-list') }}">Unpaid/Unclaimed Dividend List</a>
    <a class="{{ request()->is('admin/code-of-conduct') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/code-of-conduct') }}">Code of conduct</a>
    <a class="{{ request()->is('admin/investor-relation-department') ? 'menu_header_btn_active' : 'menu_header_btn' }}"
        href="{{ url('/admin/investor-relation-department') }}">Investor Relation Department</a>
</div>
